### Docker compose setup file
#
# This file can be used to quickly set up a development server
# with code auto-reloading

version: "3.7"

x-restart-policy: &restart_policy
  restart: always

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  olli:
    image: ghcr.io/python-discord/olli:latest
    env_file:
      .env

  web:
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:80"
    tty: true
    volumes:
      - .:/app:ro
      - staticfiles:/var/www/static
    environment:
      - APP_MODULE=website.main:app
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=site

  bot:
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -m modmail"
    volumes:
      - .:/app
    tty: true
    depends_on:
      - web
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=bot

volumes:
  staticfiles:
