[olli]
interval_minutes = 5

[loki]
api_url = "http://loki:3100"
jobs = [
    "bot", "site"
]

[discord]
WEBHOOK_URL = "YOUR DISCORD WEBHOOK URL HERE"

[[olli.tokens]]
token = "ERROR"
color = "#ff5f5f"

[[olli.tokens]]
token = "WARN"
color = "#ffe24d"
case_sensitive = true

[[olli.tokens]]
token = "INFO"
