[tool.poetry]
name = "Modmail"
version = "0.0.1"
description = "A modmail bot for Discord. Python 3.7+ compatiable"
license = "MIT"

authors = [
    "aru <genericusername414@gmail.com>",
    "bast <bast@fastmail.com"
]

maintainers = ["'ARU <genericusername414@gmail.com>"]

readme = "README.md"
repository = "https://github.com/onerandomusername/modmail"
homepage = "https://github.com/onerandomusername/modmail"
keywords = ["discord", "modmail"]

packages = [{ include = "modmail" }]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = { extras = ["speedups"], version = "^3.7.4" }
colorama = "^0.4.3"
coloredlogs = "^15.0"
"discord.py" = "1.6.0"
pydantic = "^1.8.2"
python-dotenv = "~=0.17.1"
starlette = "^0.14.2"
jinja2 = "^3.0.1"
aiofiles = "^0.7.0"
toml = "^0.10.2"
uvicorn = { extras = ["standard"], version = "^0.13.4" }

[tool.poetry.extras]
uvicorn = ["standard"]

[tool.poetry.dev-dependencies]
flake8 = "~=3.8"
black = "~=21.5b1"
flake8-annotations = "~=2.3"
flake8-bugbear = "~=20.1"
flake8-docstrings = "~=1.5"
flake8-import-order = "~=0.18"
flake8-string-format = "~=0.3"
flake8-tidy-imports = "~=4.1"
flake8-todo = "~=0.7"
pep8-naming = "~=0.11"
pre-commit = "~=2.1"
taskipy = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
bot = "python -m modmail"
site = "uvicorn main:app --app-dir website"
site-debug = "uvicorn main:app --app-dir website --reload --reload-dir website"
run = "uvicorn launcher:app --workers 1"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
black = "black --check ."
flake8 = "python -m flake8"
disttailwind = "NODE_ENV=production npx tailwindcss-cli@latest build ./src/tailwind.css -o ./static/tailwind.css"
devtailwind = "npx tailwindcss-cli@latest build ./src/tailwind.css -o ./static/tailwind.css"
export = "echo '# Do not manually edit.\n# Generate with \"poetry run task export\"\n' > requirements.txt && poetry export --without-hashes >> requirements.txt"

[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
